export const CHANGE_COOR_KEY = 'CHANGE_COOR_KEY';
export const FOCUS_CELL = 'FOCUS_CELL';
export const CHANGE_COOR_METHOD = 'CHANGE_COOR_METHOD';
export const ACTION_WITH_FORMULA = 'ACTION_WITH_FORMULA';
export const CLEAR_FOCUS_LIST = 'CLEAR_FOCUS_LIST';

